version: '3'
services:
  app:
    build:
      context: ../manager-app
      dockerfile: DockerfileProduction
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - api
  api:
    restart: always
    depends_on:
      - db
      - redis
  websocket-server:
    image: api
    volumes:
      - ./:/app
    entrypoint: php artisan websockets:serve
    depends_on:
      - api
    restart: always
  queue:
    image: api
    volumes:
      - ./:/app
    entrypoint: php artisan queue:work --verbose --tries=3 --timeout=60
    depends_on:
      - api
    restart: always
  scheduler:
    image: api
    volumes:
      - ./:/app
    entrypoint: sh -c "while true; do php artisan schedule:run --verbose & sleep 60; done"
    depends_on:
      - api
    restart: always
  db:
    restart: always
  redis:
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d/
      - ./docker/nginx/certs:/etc/nginx/certs/
      - ./docker/logs/nginx:/var/log/nginx
    restart: always