version: '3'
services:
  app:
    build:
      context: ../manager-app
      dockerfile: DockerfileProduction
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
  queue:
    restart: always
  scheduler:
    restart: always
  db:
    restart: always
  redis:
    restart: always