version: '3'
services:
  app:
    build:
      context: ../manager-app
      dockerfile: DockerfileProduction
    restart: always
    ports:
      - "8000:80"
    environment:
      VUE_APP_NAME: "ШТБП"
      VUE_APP_URL: http://localhost
      VUE_APP_MEMBER_API_URL: http://localhost:8080/admin
      VUE_APP_PUBLIC_API_URL: http://localhost:8080
  api:
    restart: always
  queue:
    restart: always
  scheduler:
    restart: always
  db:
    restart: always
  redis:
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d/
      - ./docker/nginx/certs:/etc/nginx/certs/
      - ./docker/logs/nginx:/var/log/nginx
    restart: always