version: '3'
services:
  app:
    build:
      context: ../manager-app
      dockerfile: Dockerfile.production
      args:
        VITE_APP_HOST: 164.92.253.116
        VITE_APP_NAME: "ШТБП"
    ports:
      - "80:80"
    tty: true
    stdin_open: true
    restart: always
  api:
    build:
      context: ./
    ports:
      - "8080:8080"
      - "6001:6001"
    volumes:
      - ./:/app
    env_file:
      - ./docker/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: tansultant
      DB_USERNAME: tansultant
      DB_PASSWORD: tansultant
      DB_HOST_TEST: db_test
      DB_DATABASE_TEST: test
      DB_USERNAME_TEST: test
      DB_PASSWORD_TEST: test
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      RABBITMQ_HOST: rmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
    networks:
      - tansultant_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tansultant
      POSTGRES_USER: tansultant
      POSTGRES_PASSWORD: tansultant
      PGDATA: /var/lib/postgresql/data/production/
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./docker/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - tansultant_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tansultant"]
      interval: 30s
      timeout: 10s
    restart: always
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - tansultant_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d/
      - ./docker/nginx/certs:/etc/nginx/certs/
      - ./docker/logs/nginx:/var/log/nginx
    restart: always
volumes:
  database_data:
networks:
  tansultant_network:
    external: true