version: '3'
services:
  app:
    environment:
      VITE_NAME: "ШТБП"
      VITE_URL: http://localhost
      VITE_MEMBER_API_URL: http://localhost:8080/admin
      VITE_PUBLIC_API_URL: http://localhost:8080
    build:
      context: ../manager-app
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    tty: true
    stdin_open: true
    depends_on:
      - api
    restart: always
  api:
    build:
      context: ./
    image: api
    ports:
      - "8080:8080"
      - "6001:6001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - ./docker/logs/laravel:/app/storage/logs
    env_file:
      - ./docker/.env
    environment:
      PHP_IDE_CONFIG: "serverName=docker-server"
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: tansultant
      DB_USERNAME: tansultant
      DB_PASSWORD: tansultant
      DB_HOST_TEST: db_test
      DB_DATABASE_TEST: test
      DB_USERNAME_TEST: test
      DB_PASSWORD_TEST: test
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    networks:
      - tansultant_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tansultant
      POSTGRES_USER: tansultant
      POSTGRES_PASSWORD: tansultant
      PGDATA: /var/lib/postgresql/data/production/
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./docker/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - tansultant_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tansultant"]
      interval: 30s
      timeout: 10s
    restart: always
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - tansultant_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d/
      - ./docker/nginx/certs:/etc/nginx/certs/
      - ./docker/logs/nginx:/var/log/nginx
    restart: always

volumes:
  database_data:

networks:
  tansultant_network:
    driver: bridge