version: '3'
services:
  tansultant:
    build:
      dockerfile: docker/Dockerfile
      context: ./
    ports:
      - 8100:80
    volumes:
      - ./:/app
    restart: always
    environment:
      PHP_IDE_CONFIG: "serverName=docker-server"
  db:
    build:
      dockerfile: Dockerfile
      context: ./docker/postgres
    restart: always
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"