version: '3'
services:
  app:
    build:
      context: ../manager-app
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
  scheduler:
    restart: always
  db:
    restart: always
  redis:
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d/
      - ./docker/nginx/certs:/etc/nginx/certs/
      - ./docker/logs/nginx:/var/log/nginx
    restart: always
    expose:
      - ${API_PORT}
      - ${APP_PORT}