version: '3'
services:
  app:
    build:
      context: ../manager-app
      dockerfile: DockerfileProduction
    restart: always
    ports:
      - 80:8080
  api:
    restart: always
    ports:
      - 8080:80
  queue:
    restart: always
  scheduler:
    restart: always
  db:
    restart: always
  redis:
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf:/etc/nginx/
      - ./docker/logs/nginx:/var/log/nginx
    restart: always